# Generated by Django 4.1.3 on 2022-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbersapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='output_words',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
