# Generated by Django 4.1.3 on 2022-11-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbersapi', '0002_alter_conversion_output_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='input_number',
            field=models.BigIntegerField(),
        ),
    ]
