# Generated by Django 4.1.3 on 2022-12-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("numbersapi", "0004_alter_conversion_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversion",
            options={"ordering": ["created_by"]},
        ),
    ]
