# Generated by Django 4.1.3 on 2022-12-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("numbersapi", "0006_alter_conversion_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversion",
            options={"ordering": ["created_at"]},
        ),
    ]
